# Site
name: "hassanrun"
title: "hassanrun"
description: "Kumpulan snippet code, mini tutorial, dan dokumentasi coding kita."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: ''
disqus: 'rsanhasan'
mailchimp-list: 'https://github.us13.list-manage.com/subscribe/post?u=71ede5573695e50c57ad88d84&amp;id=3fd0a89a02&amp;f_id=00a2abe2f0'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Nur Hassan
    display_name: Hassan
    gravatar: 290d1650b20de3435ca4ec69ef15f041
    email: nurhasan@tijari.id
    web: https://rsanhasan.github.io
    github: https://github.com/rsanhasan
    description: "Author of hassanrun."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
